### ISSUE TITLE
problems with "SneakToInteractItems: false"

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#51]
Using the latest commit 2d46f7f, I've found the following issues when 
"SneakToInteractItems: false" is set in the config:

1) buttons don't work
2) setting "AdminPlaceBreakBlocks: true" and with op or Parkour.Admin perm, I can break blocks but can't place blocks
3) setting "PreventOpeningCraftingInventory: false" doesn't allow me to open inventory items like chests

Conversely when 
"SneakToInteractItems: true" is set in the config, everything I've tested works as expected.

**Comment by A5H73Y** [comment]
My bad, I've fixed the side effects from point 1.
2. I'm not able to recreate this, seems to work okay on my local server?
3. That was the purpose, the only inventory you are able to open is the player inventory, based on mibbys complaint they were interacting with things outside of the course (with that in mind, they could place all the Parkour Items into a chest and repeat etc.)

**Comment by steve4744** [comment]
1. thanks.
2. I still have the same thing (when "sneak=false" and "adminPlace=true) but maybe its something on my server - I'll have another look.

3. I was just testing the reverse of what mibby actually wanted:
   so if "prevent opening" is false, then that should allow you to open inventories,
   an if "prevent opening" is true, then you are prevented from opening invs - this option works fine.

Its only in the case where "sneak=false" and "preventOpening=false" where you should be able to open chests but can't.

**Comment by A5H73Y** [comment]
Sorry Steve, I'm an idiot and forgot to push the fixes I made last night.
Please pull the latest changes, I've renamed the config for inventories in an attempt to make it more clear.

**Comment by A5H73Y** [comment]
@steve4744 Can you confirm please?

**Comment by steve4744** [comment]
Yes, that all works as it should now.

The only problem is related to #42. 
If you have an item in slot 3 of your inv hotbar before you start playing parkour, if during a game you then click the sapling to exit (or even shift click) on say a grass block, it will plant the sapling, and the item that was originally in slot 3 of your inv hotbar will be gone. If there was a stack of items in slot 3, then it will be reduced by 1. This seems to happen even if AdminPlaceBreakBlocks is false.

If you have nothing in slot3 when you start a game the sapling doesn't get planted.
